- name: "Verify access to {{ HADOOP_CONF_DIR }}"
  become: true
  become_user: "{{ SPARK_ADMIN }}"
  shell: |
    ls -lrt {{ HADOOP_CONF_DIR }}
  environment:
    HADOOP_HOME: "{{ HADOOP_HOME }}"
  ignore_errors: false

- name: "Stop cluster"
  become: true
  become_user: "{{ SPARK_ADMIN }}"
  shell: |
    {{ SPARK_HOME }}/sbin/stop-all.sh
    {{ SPARK_HOME }}/sbin/stop-history-server.sh
  environment: 
    JAVA_HOME: "{{ java_home.stdout }}"
    HADOOP_HOME: "{{ HADOOP_HOME }}"
  ignore_errors: true

- name: "Start cluster when cluster mode is standalone (currently only consider yarn mode)"
  when: SPARK_MASTER != "yarn"
  become: true
  become_user: "{{ SPARK_ADMIN }}"
  shell: |
    {{ SPARK_HOME }}/sbin/start-all.sh
  environment: 
    JAVA_HOME: "{{ java_home.stdout }}"
    HADOOP_HOME: "{{ HADOOP_HOME }}"

#--------------------------------------------------------------------------------        
# Need to create /tmp/spark-events to start history server otherwise it fails.
# See https://stackoverflow.com/questions/38350249.
#--------------------------------------------------------------------------------        
- name: "Start history server"
  become: true
  become_user: "{{ SPARK_ADMIN }}"
  shell: |
    echo "https://stackoverflow.com/questions/38350249"
    mkdir -p /tmp/spark-events
    {{ SPARK_HOME }}/sbin/start-history-server.sh
  environment: 
    JAVA_HOME: "{{ java_home.stdout }}"
    HADOOP_HOME: "{{ HADOOP_HOME }}"
